name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build & Install
      run: mvn -B install -DskipTests --no-transfer-progress

    - name: Install Playwright
      run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

    - name: Run tests
      run: mvn test

    - name: List test-reports directory for debugging
      run: ls -R target/test-reports

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/test-reports/*.html  # Adjust this path if your reports are generated elsewhere

